# This YAML file contains the configuration for a Ray cluster.
# It specifies the cluster name, provider type, IP addresses of the head and worker nodes,
cluster_name: vit-ray

# Run ray in containers
docker: 
  image: "ml-service-old"
  container_name: "ml-service-old"
  pull_before_run: false
  run_options:
    - --runtime=nvidia
    - --gpus all
    - --ipc=host
    - --privileged
    - -v "/data/navin-kumar-m":"/data"
    - -p 8000:8000

# The 'provider' section specifies the type of provider and the IP addresses of the head node and worker nodes.
provider:
  type: local
  head_ip: 172.16.0.57
  worker_ips: []
   
auth:
  ssh_user: administrator  # The SSH username for authentication
  ssh_private_key: ~/.ssh/id_rsa_vit

min_workers: 0  # Minimum number of workers in the cluster
max_workers: 0  # Maximum number of workers in the cluster
upscaling_speed: 1.0  # Speed at which the cluster scales up
idle_timeout_minutes: 3  # Timeout in minutes for idle workers to be terminated

#file_mounts: {
#  "/app":"."  
#}

#rsync_exclude:
#  - "**/.git"
#  - "**/.git/**"
#  - "*.tar.*"

#rsync_filter:
#  - ".gitignore"
#  - "__pycache__"
#  - "=*"
#  - "*.pyc"
#  - "*.tar.*"
#  - ".git"


#file_mounts_sync_continuously: true

setup_commands: []

# This YAML file contains the configuration for starting and stopping Ray clusters.
head_start_ray_commands:
  - ray stop
  - ulimit -c unlimited && ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml --dashboard-host=0.0.0.0  --object-manager-port=8076

# The commands to start Ray workers in the cluster.
worker_start_ray_commands:
  - ray stop
  - export RAY_HEAD_IP && echo "export RAY_HEAD_IP=$RAY_HEAD_IP" >> ~/.bashrc && ray start --address=$RAY_HEAD_IP:6379   --object-manager-port=8076
