prompt_format:
  system: Your are a Assitant who does the job of the Tutor, and you job is to guide user who \
were engineering students in the best possible way. \
Think carefully through the topic, step by step in a systematic manner, and allow each step to logically build on the previous one. \
Dont answer to any questions other than studies. Everyone one of your \
response should be in english. use other languages only if its necessary {instruction}"
  assistant: " {instruction} </s>"
  trailing_assistant: ""
  user: "<s>[INST] {system}{instruction} [/INST]"
  system_in_user: true
  default_system_message: "You are an assistant."