# Required
version: 2

mkdocs:
  configuration: mkdocs.yml

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/requirements.txt
