[tool.poetry]
name = "ai-lp"
version = "0.1.0"
description = "Education-AI is a LLM model with RAG pipeline which behaves like a guide and able to solve doubts"
authors = ["Navin Kumar M"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
fastapi = "0.108.0"
vllm = "^0.4.0"