llm:
  max_tokens: 4096
  temperature: 0.3

store:
  name: qdrant
  infer:
    min_score: 0.001
    limit: 1
  main:
    collection_name: megacad
    host: qdrant
    dim: 1024
    distance: Cosine

  config:
    url: qdrant
    port: "6333"
    prefer_grpc: True
    timeout: 5

  create_collection:
    collection_name: "example_collection"
    dim: 1024
    distance: "cosine"
    timeout: 5
    hnsw_config:
      m: 10
      ef_construct: 10
    quantization_config:
      quantile: 0.99
    
  index_payload: course
  
