version: '3'
services:
  postgres:
    build: ./docker/postgres/
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  cassandra:
    build: ./docker/cassandra/
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
      - CASSANDRA_ENDPOINT_SNITCH=${CASSANDRA_ENDPOINT_SNITCH}
      - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
  qdrant:
    build: ./docker/qdrant/
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
  ml_service:
    build: ./docker/ml_service
    ports:
      - "5000:5000"
    environment:
      - ML_SERVICE_HOST=${ML_SERVICE_HOST}
      - ML_SERVICE_PORT=${ML_SERVICE_PORT}
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - CASSANDRA_HOST=${CASSANDRA_HOST}
      - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
      - CASSANDRA_USER=${CASSANDRA_USER}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
      - QDRANT_COLLECTION_NAME=${QDRANT_COLLECTION_NAME}
      - QDRANT_HOST=${QDRANT_HOST}
    depends_on:
      - postgres
      - cassandra
      - qdrant
      - ml_service
      
    
      

volumes:
  postgres_data:
  cassandra_data:
  qdrant_data:
