version: '3'
services:
  postgres:
    build: ./docker/postgres/
    networks: 
      - server-net

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  cassandra:
    build: ./docker/cassandra/
    networks: 
      - server-net

    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
      - CASSANDRA_ENDPOINT_SNITCH=${CASSANDRA_ENDPOINT_SNITCH}
      - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
  qdrant:
    build: ./docker/qdrant/
    networks: 
     - server-net

    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
  web:
    build: .
    networks:
     - server-net
    volumes:
      - .:/app
    ports:
      - "9999:8000"
    environment:
      - DJANGO_DEBUG=True
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - CASSANDRA_HOST=${CASSANDRA_HOST}
      - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
      - CASSANDRA_USER=${CASSANDRA_USER}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
      - QDRANT_COLLECTION_NAME=${QDRANT_COLLECTION_NAME}
      - QDRANT_HOST=${QDRANT_HOST}
    depends_on:
      - postgres
      - cassandra
      - qdrant

volumes:
  postgres_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/ailp-server/postgres_data
  cassandra_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/ailp-server/cassandra_data
  qdrant_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/ailp-server/qdrant_data

networks:
  server-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
