version: '3'
services:
  postgres:
    image: ailp-prod_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  cassandra:
    image: ailp-prod_cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
      - CASSANDRA_ENDPOINT_SNITCH=${CASSANDRA_ENDPOINT_SNITCH}
      - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
  qdrant:
    image: ailp-prod_qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
  web:
    image: ailp-prod_web
    volumes:
      - .:/app
    ports:
      - "9999:8000"
    environment:
      - DJANGO_DEBUG=false
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - CASSANDRA_HOST=${CASSANDRA_HOST}
      - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
      - CASSANDRA_USER=${CASSANDRA_USER}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
      - QDRANT_COLLECTION_NAME=${QDRANT_COLLECTION_NAME}
      - QDRANT_HOST=${QDRANT_HOST}
    depends_on:
      - postgres
      - cassandra
      - qdrant
      - ml_service
      
volumes:
  postgres_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/ailp-server/postgres_data
  cassandra_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/ailp-server/cassandra_data
  qdrant_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/ailp-server/qdrant_data

      