[tool.poetry]
name = "ai-lms"
version = "0.1.0"
description = ""
authors = ["Entropy <70720874+NavinKumarMNK@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.8"
django = "4.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
