# This YAML file contains the configuration for a Ray cluster.
# It specifies the cluster name, provider type, IP addresses of the head and worker nodes,
cluster_name: vit-ray

# The 'provider' section specifies the type of provider and the IP addresses of the head node and worker nodes.
provider:
  type: local
  head_ip: 172.16.96.62
  worker_ips: [172.16.96.60, 172.16.96.61, 172.16.96.59, 172.16.96.64, 172.16.96.66, 172.16.96.68]
   
auth:
  ssh_user: vit  # The SSH username for authentication

min_workers: 6  # Minimum number of workers in the cluster
max_workers: 6  # Maximum number of workers in the cluster
upscaling_speed: 1.0  # Speed at which the cluster scales up
idle_timeout_minutes: 3  # Timeout in minutes for idle workers to be terminated

file_mounts: {
  "/home/vit/AI-LMS":"/home/vit/AI-LMS"
}

file_mounts_sync_continuously: false

setup_commands: [
#  pip3 install --upgrade pip,
 pip3 install -r /home/vit/AI-LMS/requirements.txt
]

# This YAML file contains the configuration for starting and stopping Ray clusters.
head_start_ray_commands:
  - ray stop
  - ulimit -c unlimited && ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml
# The commands to start Ray workers in the cluster.
worker_start_ray_commands:
  - ray stop
  - ray start --address=$RAY_HEAD_IP:6379
